name: 수정본240분.yml

on: 
  schedule:
    - cron: 50 3,7,11,15,19 * * *
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint python-telegram-bot requests pandas numpy telegram
    - name: run
      run: |
        python 수정본240분.py
